name: choice
on: 
   workflow_dispatch:
    inputs:
      action:
        description: 'Terraform Action to Perform'
        type: choice
        options:
        - Terraform_apply
        - Terraform_destroy
jobs:
  terraform:
    name: Action
    runs-on: amazon-linux
    steps:
    - name: My first step - check out repository
      uses: actions/checkout@v4
    - name: apply
      uses: ./.github/actions/terraform-apply.yml
      